[2025-01-14T03:08:46.322+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-14T03:08:46.358+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_mysql_connector_sqlalchemy.test_mysql_connection manual__2025-01-14T03:08:43.637948+00:00 [queued]>
[2025-01-14T03:08:46.397+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_mysql_connector_sqlalchemy.test_mysql_connection manual__2025-01-14T03:08:43.637948+00:00 [queued]>
[2025-01-14T03:08:46.397+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-14T03:08:46.430+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_mysql_connection> on 2025-01-14 03:08:43.637948+00:00
[2025-01-14T03:08:46.456+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=87) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-14T03:08:46.461+0000] {standard_task_runner.py:72} INFO - Started process 88 to run task
[2025-01-14T03:08:46.456+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_mysql_connector_sqlalchemy', 'test_mysql_connection', 'manual__2025-01-14T03:08:43.637948+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/test_mysql_connector.py', '--cfg-path', '/tmp/tmp_2o3mecf']
[2025-01-14T03:08:46.469+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask test_mysql_connection
[2025-01-14T03:08:46.642+0000] {task_command.py:467} INFO - Running <TaskInstance: test_mysql_connector_sqlalchemy.test_mysql_connection manual__2025-01-14T03:08:43.637948+00:00 [running]> on host 1c765e14a650
[2025-01-14T03:08:46.991+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_mysql_connector_sqlalchemy' AIRFLOW_CTX_TASK_ID='test_mysql_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T03:08:43.637948+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-14T03:08:43.637948+00:00'
[2025-01-14T03:08:46.992+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-14T03:08:47.150+0000] {logging_mixin.py:190} INFO - Connected to database: data_crawl
[2025-01-14T03:08:47.155+0000] {logging_mixin.py:190} INFO - MySQL connection closed.
[2025-01-14T03:08:47.156+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-14T03:08:47.199+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-14T03:08:47.200+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_mysql_connector_sqlalchemy, task_id=test_mysql_connection, run_id=manual__2025-01-14T03:08:43.637948+00:00, execution_date=20250114T030843, start_date=20250114T030846, end_date=20250114T030847
[2025-01-14T03:08:47.307+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-14T03:08:47.355+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-14T03:08:47.419+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
