[2025-01-14T02:13:57.127+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-14T02:13:57.145+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_mysql_connector_sqlalchemy.test_mysql_connection manual__2025-01-14T02:13:55.686722+00:00 [queued]>
[2025-01-14T02:13:57.157+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_mysql_connector_sqlalchemy.test_mysql_connection manual__2025-01-14T02:13:55.686722+00:00 [queued]>
[2025-01-14T02:13:57.158+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-14T02:13:57.174+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_mysql_connection> on 2025-01-14 02:13:55.686722+00:00
[2025-01-14T02:13:57.180+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=67) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-14T02:13:57.182+0000] {standard_task_runner.py:72} INFO - Started process 68 to run task
[2025-01-14T02:13:57.182+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_mysql_connector_sqlalchemy', 'test_mysql_connection', 'manual__2025-01-14T02:13:55.686722+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/test_mysql_connector.py', '--cfg-path', '/tmp/tmpdjhksv6v']
[2025-01-14T02:13:57.183+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask test_mysql_connection
[2025-01-14T02:13:57.243+0000] {task_command.py:467} INFO - Running <TaskInstance: test_mysql_connector_sqlalchemy.test_mysql_connection manual__2025-01-14T02:13:55.686722+00:00 [running]> on host 4da24070c35c
[2025-01-14T02:13:57.358+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_mysql_connector_sqlalchemy' AIRFLOW_CTX_TASK_ID='test_mysql_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T02:13:55.686722+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-14T02:13:55.686722+00:00'
[2025-01-14T02:13:57.359+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-14T02:13:57.411+0000] {test_mysql_connector.py:23} ERROR - Couldn't create the MySQL connection due to: (MySQLdb.OperationalError) (2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-01-14T02:13:57.411+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-14T02:13:57.421+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-14T02:13:57.421+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_mysql_connector_sqlalchemy, task_id=test_mysql_connection, run_id=manual__2025-01-14T02:13:55.686722+00:00, execution_date=20250114T021355, start_date=20250114T021357, end_date=20250114T021357
[2025-01-14T02:13:57.441+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-14T02:13:57.454+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-14T02:13:57.457+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
