[2025-01-13T10:16:13.297+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-13T10:16:13.316+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: topcv_scraper.extract_job_data manual__2025-01-13T10:06:24.100128+00:00 [queued]>
[2025-01-13T10:16:13.326+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: topcv_scraper.extract_job_data manual__2025-01-13T10:06:24.100128+00:00 [queued]>
[2025-01-13T10:16:13.327+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-13T10:16:13.342+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_job_data> on 2025-01-13 10:06:24.100128+00:00
[2025-01-13T10:16:13.349+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=369) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-13T10:16:13.351+0000] {standard_task_runner.py:72} INFO - Started process 370 to run task
[2025-01-13T10:16:13.357+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'topcv_scraper', 'extract_job_data', 'manual__2025-01-13T10:06:24.100128+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/crawl_data.py', '--cfg-path', '/tmp/tmps3a9eyrf']
[2025-01-13T10:16:13.360+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask extract_job_data
[2025-01-13T10:16:13.414+0000] {task_command.py:467} INFO - Running <TaskInstance: topcv_scraper.extract_job_data manual__2025-01-13T10:06:24.100128+00:00 [running]> on host c9148da66659
[2025-01-13T10:16:13.700+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='topcv_scraper' AIRFLOW_CTX_TASK_ID='extract_job_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T10:06:24.100128+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T10:06:24.100128+00:00'
[2025-01-13T10:16:13.702+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-13T10:16:54.571+0000] {logging_mixin.py:190} INFO - MySQL error: 2003 (HY000): Can't connect to MySQL server on 'localhost:3307' (111)
[2025-01-13T10:16:54.571+0000] {logging_mixin.py:190} INFO - An unexpected error occurred: cannot access local variable 'conn' where it is not associated with a value
[2025-01-13T10:16:54.572+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-13T10:16:54.583+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-13T10:16:54.583+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=topcv_scraper, task_id=extract_job_data, run_id=manual__2025-01-13T10:06:24.100128+00:00, execution_date=20250113T100624, start_date=20250113T101613, end_date=20250113T101654
[2025-01-13T10:16:54.630+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-13T10:16:54.643+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-13T10:16:54.645+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
