[2025-01-14T01:36:59.577+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-14T01:36:59.594+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_mysql_connector.test_mysql_connection manual__2025-01-14T01:36:57.407497+00:00 [queued]>
[2025-01-14T01:36:59.601+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_mysql_connector.test_mysql_connection manual__2025-01-14T01:36:57.407497+00:00 [queued]>
[2025-01-14T01:36:59.602+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-14T01:36:59.616+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_mysql_connection> on 2025-01-14 01:36:57.407497+00:00
[2025-01-14T01:36:59.622+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=183) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-14T01:36:59.624+0000] {standard_task_runner.py:72} INFO - Started process 184 to run task
[2025-01-14T01:36:59.624+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_mysql_connector', 'test_mysql_connection', 'manual__2025-01-14T01:36:57.407497+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/test_mysql_connector.py', '--cfg-path', '/tmp/tmpou0wf7_f']
[2025-01-14T01:36:59.630+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask test_mysql_connection
[2025-01-14T01:36:59.687+0000] {task_command.py:467} INFO - Running <TaskInstance: test_mysql_connector.test_mysql_connection manual__2025-01-14T01:36:57.407497+00:00 [running]> on host d57747bc7b0c
[2025-01-14T01:36:59.765+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_mysql_connector' AIRFLOW_CTX_TASK_ID='test_mysql_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T01:36:57.407497+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-14T01:36:57.407497+00:00'
[2025-01-14T01:36:59.766+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-14T01:36:59.782+0000] {test_mysql_connector.py:39} ERROR - Couldn't create the MySQL connection due to: 2003 (HY000): Can't connect to MySQL server on 'localhost:3307' (111)
[2025-01-14T01:36:59.783+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-14T01:36:59.791+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-14T01:36:59.792+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_mysql_connector, task_id=test_mysql_connection, run_id=manual__2025-01-14T01:36:57.407497+00:00, execution_date=20250114T013657, start_date=20250114T013659, end_date=20250114T013659
[2025-01-14T01:36:59.818+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-14T01:36:59.836+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-14T01:36:59.839+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
