[2025-01-13T02:38:06.691+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-13T02:38:06.732+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: topcv_scraper.extract_job_data manual__2025-01-13T02:10:49.382707+00:00 [queued]>
[2025-01-13T02:38:06.758+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: topcv_scraper.extract_job_data manual__2025-01-13T02:10:49.382707+00:00 [queued]>
[2025-01-13T02:38:06.759+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-13T02:38:06.799+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_job_data> on 2025-01-13 02:10:49.382707+00:00
[2025-01-13T02:38:06.816+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=364) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-13T02:38:06.827+0000] {standard_task_runner.py:72} INFO - Started process 365 to run task
[2025-01-13T02:38:06.811+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'topcv_scraper', 'extract_job_data', 'manual__2025-01-13T02:10:49.382707+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/crawl_data.py', '--cfg-path', '/tmp/tmpfwlj7w3x']
[2025-01-13T02:38:06.839+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask extract_job_data
[2025-01-13T02:38:06.934+0000] {task_command.py:467} INFO - Running <TaskInstance: topcv_scraper.extract_job_data manual__2025-01-13T02:10:49.382707+00:00 [running]> on host 91a339479d94
[2025-01-13T02:38:10.434+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='topcv_scraper' AIRFLOW_CTX_TASK_ID='extract_job_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T02:10:49.382707+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T02:10:49.382707+00:00'
[2025-01-13T02:38:10.437+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-13T02:39:15.830+0000] {logging_mixin.py:190} INFO - An error occurred: 2003 (HY000): Can't connect to MySQL server on 'localhost:3307' (111)
[2025-01-13T02:39:15.831+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-13T02:39:15.850+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-13T02:39:15.851+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=topcv_scraper, task_id=extract_job_data, run_id=manual__2025-01-13T02:10:49.382707+00:00, execution_date=20250113T021049, start_date=20250113T023806, end_date=20250113T023915
[2025-01-13T02:39:15.967+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-13T02:39:16.003+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-13T02:39:16.011+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
