[2025-01-14T02:15:12.134+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-14T02:15:12.151+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_mysql_connector_sqlalchemy.test_mysql_connection manual__2025-01-14T02:15:10.556979+00:00 [queued]>
[2025-01-14T02:15:12.159+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_mysql_connector_sqlalchemy.test_mysql_connection manual__2025-01-14T02:15:10.556979+00:00 [queued]>
[2025-01-14T02:15:12.160+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-14T02:15:12.173+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_mysql_connection> on 2025-01-14 02:15:10.556979+00:00
[2025-01-14T02:15:12.179+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-14T02:15:12.181+0000] {standard_task_runner.py:72} INFO - Started process 85 to run task
[2025-01-14T02:15:12.181+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_mysql_connector_sqlalchemy', 'test_mysql_connection', 'manual__2025-01-14T02:15:10.556979+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/test_mysql_connector.py', '--cfg-path', '/tmp/tmpmc7y7unl']
[2025-01-14T02:15:12.182+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask test_mysql_connection
[2025-01-14T02:15:12.224+0000] {task_command.py:467} INFO - Running <TaskInstance: test_mysql_connector_sqlalchemy.test_mysql_connection manual__2025-01-14T02:15:10.556979+00:00 [running]> on host 4da24070c35c
[2025-01-14T02:15:12.307+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_mysql_connector_sqlalchemy' AIRFLOW_CTX_TASK_ID='test_mysql_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T02:15:10.556979+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-14T02:15:10.556979+00:00'
[2025-01-14T02:15:12.308+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-14T02:15:12.331+0000] {test_mysql_connector.py:24} ERROR - Couldn't create the MySQL connection due to: (MySQLdb.OperationalError) (2002, "Can't connect to server on 'mysql' (115)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-01-14T02:15:12.331+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-14T02:15:12.341+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-14T02:15:12.341+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_mysql_connector_sqlalchemy, task_id=test_mysql_connection, run_id=manual__2025-01-14T02:15:10.556979+00:00, execution_date=20250114T021510, start_date=20250114T021512, end_date=20250114T021512
[2025-01-14T02:15:12.358+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-14T02:15:12.373+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-14T02:15:12.375+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
