[2025-01-14T01:35:56.107+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-14T01:35:56.122+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_mysql_connector.test_mysql_connection manual__2025-01-14T01:35:53.954056+00:00 [queued]>
[2025-01-14T01:35:56.129+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_mysql_connector.test_mysql_connection manual__2025-01-14T01:35:53.954056+00:00 [queued]>
[2025-01-14T01:35:56.130+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-14T01:35:56.141+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_mysql_connection> on 2025-01-14 01:35:53.954056+00:00
[2025-01-14T01:35:56.146+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=166) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-14T01:35:56.148+0000] {standard_task_runner.py:72} INFO - Started process 167 to run task
[2025-01-14T01:35:56.148+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_mysql_connector', 'test_mysql_connection', 'manual__2025-01-14T01:35:53.954056+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/test_mysql_connector.py', '--cfg-path', '/tmp/tmp76_vq5z1']
[2025-01-14T01:35:56.149+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask test_mysql_connection
[2025-01-14T01:35:56.192+0000] {task_command.py:467} INFO - Running <TaskInstance: test_mysql_connector.test_mysql_connection manual__2025-01-14T01:35:53.954056+00:00 [running]> on host d57747bc7b0c
[2025-01-14T01:35:56.263+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_mysql_connector' AIRFLOW_CTX_TASK_ID='test_mysql_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T01:35:53.954056+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-14T01:35:53.954056+00:00'
[2025-01-14T01:35:56.264+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-14T01:35:56.292+0000] {test_mysql_connector.py:39} ERROR - Couldn't create the MySQL connection due to: 2003 (HY000): Can't connect to MySQL server on 'localhost:3307' (111)
[2025-01-14T01:35:56.292+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-14T01:35:56.301+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-14T01:35:56.301+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_mysql_connector, task_id=test_mysql_connection, run_id=manual__2025-01-14T01:35:53.954056+00:00, execution_date=20250114T013553, start_date=20250114T013556, end_date=20250114T013556
[2025-01-14T01:35:56.322+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-14T01:35:56.336+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-14T01:35:56.339+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
