[2025-01-14T01:23:26.450+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-14T01:23:26.489+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_mysql_connector.test_mysql_connection manual__2025-01-14T01:23:24.978273+00:00 [queued]>
[2025-01-14T01:23:26.502+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_mysql_connector.test_mysql_connection manual__2025-01-14T01:23:24.978273+00:00 [queued]>
[2025-01-14T01:23:26.502+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-14T01:23:26.522+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_mysql_connection> on 2025-01-14 01:23:24.978273+00:00
[2025-01-14T01:23:26.532+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=255) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-14T01:23:26.538+0000] {standard_task_runner.py:72} INFO - Started process 256 to run task
[2025-01-14T01:23:26.540+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_mysql_connector', 'test_mysql_connection', 'manual__2025-01-14T01:23:24.978273+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/test_mysql_connector.py', '--cfg-path', '/tmp/tmpirwd47f8']
[2025-01-14T01:23:26.542+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask test_mysql_connection
[2025-01-14T01:23:26.603+0000] {task_command.py:467} INFO - Running <TaskInstance: test_mysql_connector.test_mysql_connection manual__2025-01-14T01:23:24.978273+00:00 [running]> on host 203688f735a9
[2025-01-14T01:23:26.722+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_mysql_connector' AIRFLOW_CTX_TASK_ID='test_mysql_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T01:23:24.978273+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-14T01:23:24.978273+00:00'
[2025-01-14T01:23:26.723+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-14T01:23:26.750+0000] {test_mysql_connector.py:39} ERROR - Couldn't create the MySQL connection due to: 2003 (HY000): Can't connect to MySQL server on 'localhost:3307' (111)
[2025-01-14T01:23:26.751+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-14T01:23:26.764+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-14T01:23:26.766+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_mysql_connector, task_id=test_mysql_connection, run_id=manual__2025-01-14T01:23:24.978273+00:00, execution_date=20250114T012324, start_date=20250114T012326, end_date=20250114T012326
[2025-01-14T01:23:26.795+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-14T01:23:26.823+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-14T01:23:26.826+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
