[2025-01-13T12:35:08.654+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-13T12:35:08.673+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: topcv_scraper.extract_job_data manual__2025-01-13T12:26:15.634189+00:00 [queued]>
[2025-01-13T12:35:08.687+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: topcv_scraper.extract_job_data manual__2025-01-13T12:26:15.634189+00:00 [queued]>
[2025-01-13T12:35:08.687+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-13T12:35:08.706+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_job_data> on 2025-01-13 12:26:15.634189+00:00
[2025-01-13T12:35:08.713+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=194) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-13T12:35:08.714+0000] {standard_task_runner.py:72} INFO - Started process 195 to run task
[2025-01-13T12:35:08.718+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'topcv_scraper', 'extract_job_data', 'manual__2025-01-13T12:26:15.634189+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/crawl_data.py', '--cfg-path', '/tmp/tmpi1e789rw']
[2025-01-13T12:35:08.723+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask extract_job_data
[2025-01-13T12:35:08.773+0000] {task_command.py:467} INFO - Running <TaskInstance: topcv_scraper.extract_job_data manual__2025-01-13T12:26:15.634189+00:00 [running]> on host 30039af1025f
[2025-01-13T12:35:09.133+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='topcv_scraper' AIRFLOW_CTX_TASK_ID='extract_job_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T12:26:15.634189+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T12:26:15.634189+00:00'
[2025-01-13T12:35:09.134+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-13T12:35:22.012+0000] {logging_mixin.py:190} INFO - MySQL error: 2003 (HY000): Can't connect to MySQL server on 'localhost:3307' (111)
[2025-01-13T12:35:22.012+0000] {logging_mixin.py:190} INFO - An unexpected error occurred: cannot access local variable 'conn' where it is not associated with a value
[2025-01-13T12:35:22.013+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-13T12:35:22.022+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-13T12:35:22.022+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=topcv_scraper, task_id=extract_job_data, run_id=manual__2025-01-13T12:26:15.634189+00:00, execution_date=20250113T122615, start_date=20250113T123508, end_date=20250113T123522
[2025-01-13T12:35:22.076+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-13T12:35:22.090+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-13T12:35:22.094+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
