[2025-01-14T01:10:05.639+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-14T01:10:05.654+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_mysql_connector.test_mysql_connection manual__2025-01-14T01:01:44.704672+00:00 [queued]>
[2025-01-14T01:10:05.661+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_mysql_connector.test_mysql_connection manual__2025-01-14T01:01:44.704672+00:00 [queued]>
[2025-01-14T01:10:05.662+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-14T01:10:05.676+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_mysql_connection> on 2025-01-14 01:01:44.704672+00:00
[2025-01-14T01:10:05.681+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=59) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-14T01:10:05.683+0000] {standard_task_runner.py:72} INFO - Started process 60 to run task
[2025-01-14T01:10:05.688+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_mysql_connector', 'test_mysql_connection', 'manual__2025-01-14T01:01:44.704672+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/test_mysql_connector.py', '--cfg-path', '/tmp/tmpih0l7i5v']
[2025-01-14T01:10:05.690+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask test_mysql_connection
[2025-01-14T01:10:05.731+0000] {task_command.py:467} INFO - Running <TaskInstance: test_mysql_connector.test_mysql_connection manual__2025-01-14T01:01:44.704672+00:00 [running]> on host 203688f735a9
[2025-01-14T01:10:05.814+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_mysql_connector' AIRFLOW_CTX_TASK_ID='test_mysql_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T01:01:44.704672+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-14T01:01:44.704672+00:00'
[2025-01-14T01:10:05.815+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-14T01:10:05.849+0000] {logging_mixin.py:190} INFO - Lá»—i MySQL: 2003 (HY000): Can't connect to MySQL server on 'mysql:3307' (111)
[2025-01-14T01:10:05.849+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_mysql_connector.py", line 30, in test_mysql_connection
    if conn.is_connected():
       ^^^^
UnboundLocalError: cannot access local variable 'conn' where it is not associated with a value
[2025-01-14T01:10:05.860+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=test_mysql_connector, task_id=test_mysql_connection, run_id=manual__2025-01-14T01:01:44.704672+00:00, execution_date=20250114T010144, start_date=20250114T011005, end_date=20250114T011005
[2025-01-14T01:10:05.871+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-14T01:10:05.872+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task test_mysql_connection (cannot access local variable 'conn' where it is not associated with a value; 60)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_mysql_connector.py", line 30, in test_mysql_connection
    if conn.is_connected():
       ^^^^
UnboundLocalError: cannot access local variable 'conn' where it is not associated with a value
[2025-01-14T01:10:05.899+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-14T01:10:05.912+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-14T01:10:05.917+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
