[2025-01-10T13:26:07.016+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-10T13:26:07.032+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_insert_jobs.insert_jobs manual__2025-01-10T13:21:46.280884+00:00 [queued]>
[2025-01-10T13:26:07.041+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_insert_jobs.insert_jobs manual__2025-01-10T13:21:46.280884+00:00 [queued]>
[2025-01-10T13:26:07.042+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-10T13:26:07.056+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): insert_jobs> on 2025-01-10 13:21:46.280884+00:00
[2025-01-10T13:26:07.063+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=129) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-10T13:26:07.065+0000] {standard_task_runner.py:72} INFO - Started process 130 to run task
[2025-01-10T13:26:07.065+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_insert_jobs', 'insert_jobs', 'manual__2025-01-10T13:21:46.280884+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/crawl_data.py', '--cfg-path', '/tmp/tmpvswxdjrp']
[2025-01-10T13:26:07.068+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask insert_jobs
[2025-01-10T13:26:07.110+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_and_insert_jobs.insert_jobs manual__2025-01-10T13:21:46.280884+00:00 [running]> on host 168926f0adfc
[2025-01-10T13:26:07.179+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_and_insert_jobs' AIRFLOW_CTX_TASK_ID='insert_jobs' AIRFLOW_CTX_EXECUTION_DATE='2025-01-10T13:21:46.280884+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-10T13:21:46.280884+00:00'
[2025-01-10T13:26:07.181+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-10T13:26:10.882+0000] {logging_mixin.py:190} INFO - Failed to retrieve page 1. Status code: 429
[2025-01-10T13:26:15.998+0000] {logging_mixin.py:190} INFO - Failed to retrieve page 2. Status code: 429
[2025-01-10T13:26:19.583+0000] {logging_mixin.py:190} INFO - Failed to retrieve page 3. Status code: 429
[2025-01-10T13:26:23.576+0000] {logging_mixin.py:190} INFO - Failed to retrieve page 4. Status code: 429
[2025-01-10T13:26:28.203+0000] {logging_mixin.py:190} INFO - Failed to retrieve page 5. Status code: 429
[2025-01-10T13:26:32.604+0000] {logging_mixin.py:190} INFO - Failed to retrieve page 6. Status code: 429
[2025-01-10T13:26:37.816+0000] {logging_mixin.py:190} INFO - Failed to retrieve page 7. Status code: 429
[2025-01-10T13:26:41.103+0000] {logging_mixin.py:190} INFO - Failed to retrieve page 8. Status code: 429
[2025-01-10T13:26:46.018+0000] {logging_mixin.py:190} INFO - Failed to retrieve page 9. Status code: 429
[2025-01-10T13:26:50.914+0000] {logging_mixin.py:190} INFO - Failed to retrieve page 10. Status code: 429
[2025-01-10T13:26:50.915+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawl_data.py", line 110, in insert_jobs
    urls = scrape_urls()
           ^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawl_data.py", line 55, in scrape_urls
    kwargs['ti'].xcom_push(key='urls', value=urls)
    ~~~~~~^^^^^^
KeyError: 'ti'
[2025-01-10T13:26:50.925+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=scrape_and_insert_jobs, task_id=insert_jobs, run_id=manual__2025-01-10T13:21:46.280884+00:00, execution_date=20250110T132146, start_date=20250110T132607, end_date=20250110T132650
[2025-01-10T13:26:50.943+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-10T13:26:50.944+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task insert_jobs ('ti'; 130)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawl_data.py", line 110, in insert_jobs
    urls = scrape_urls()
           ^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawl_data.py", line 55, in scrape_urls
    kwargs['ti'].xcom_push(key='urls', value=urls)
    ~~~~~~^^^^^^
KeyError: 'ti'
[2025-01-10T13:26:50.962+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-10T13:26:50.975+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-10T13:26:50.977+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
